test_anagram (__main__.TestExercice) ... ERROR
test_doubles (__main__.TestExercice) ... ok
test_frequence (__main__.TestExercice) ... ok
test_grades (__main__.TestExercice) ... ok
test_order (__main__.TestExercice) ... ok

======================================================================
ERROR: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 35, in test_anagram
    output = [exercice.anagrams(v) for v in words]
  File "test_exercice.py", line 35, in <listcomp>
    output = [exercice.anagrams(v) for v in words]
  File "/home/runner/work/c04-ch6-exercices-premyskw/c04-ch6-exercices-premyskw/exercice.py", line 24, in anagrams
    return anagramme
UnboundLocalError: local variable 'anagramme' referenced before assignment

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
